enhance(DiscreteBarChart): Improve readability of DiscreteBar value and year labels
owid/owid-grapher pull request #1368
Opened 2022-04-06 21:42 UTC by BhCh7051

This PR closes #1347.
Improved readability and updated DiscreteBarChart.test to take changes into account

It now looks like this:
![average-working-hours-of-children](https://user-images.githubusercontent.com/56021613/162074604-84d602bb-39fb-4925-b71f-07e70b5f1679.png)

2022-04-08 15:37 UTC, danyx23 requested changes
Hi @BhCh7051, thanks a lot for working on this! This already looks good but I have one request: you chose to switch from a single string to an array of two strings. Could you instead use an object and define an interface type for it please? I think that this will be easier to maintain in the long term. The member names could be something like .valueString and .yearString. Thank you!

I'll be away for a few days so I'd like @danielgavrilov to do the final review please - thank you!

2022-04-09 23:17 UTC, BhCh7051 commented
Implemented changes suggested by @danyx23. Re-requesting reviews.

2022-04-11 10:46 UTC, danielgavrilov requested changes
Hi @BhCh7051, awesome job, thank you very much for working on this! I have some minor suggestions – if you run into any trouble implementing them, let me know!

2022-04-11 10:46 UTC, danielgavrilov commented on grapher/barCharts/DiscreteBarChart.tsx
> +    yearString: string
I think a better name would be `timeString`? Since it could be year or date (for now, probably more in the future).

2022-04-11 10:46 UTC, danielgavrilov commented on grapher/barCharts/DiscreteBarChart.tsx
> +                ? ` in ${transformedTable.timeColumnFormatFunction(
The proposition `in` works for years, but not for dates, e.g. `in April 28` is somewhat incorrect, it needs to be `on April 28`.

I think you can copy the implementation from the map tooltip here: https://github.com/owid/owid-grapher/blob/e925bd457c20da71aaf0d8ac5a279a63a430edee/grapher/mapCharts/MapTooltip.tsx#L188


I think something along these lines should work:

```suggestion
                ? ` ${transformedTable.getPreposition(transformedTable.timeColumn)} ${transformedTable.timeColumnFormatFunction(
```

2022-04-11 14:52 UTC, BhCh7051 commented
Implemented changes suggested by @danielgavrilov. Re-requesting reviews.

2022-04-11 16:14 UTC, merged