feature(DetailsOnDemand): initial desktop implementation
owid/owid-grapher pull request #1503
Opened 2022-06-17 22:00 UTC by ikesau

Resolves #1497 

Brought in `markdown-to-jsx` (5kB) to render the tooltip contents. In my experience it's a very useful library to have around, but if we don't want to bring it in, I can write a custom parser. 

The span logic is a little gnarly, I need to make sure that it will work for the SVG implementation also (which I'll do in a separate PR) hence the draft status.

https://user-images.githubusercontent.com/11844404/174406038-93bfdfaf-2dca-43e9-b8a7-ed368444b61a.mov

2022-06-22 10:00 UTC, danielgavrilov requested changes
I mentioned in a comment – can check if `tippy` is a good fit for the tooltip.

I'm also hesitant about parsing DoD in the `TextWrap` component like this, feels like the parsing logic should maybe be outside the text-wrapping procedure? Are there other options you considered? I'm thinking about how we might extend this to support bold, italic in subtitles eventually. 

Could we maybe pass tokenised input to `TextWrap`? Or even `TextWrap` itself could be implemented in two steps – parse markdown to produce tokens, then try to wrap those tokens. 

Also related: do Markdown parsing libraries handle the `[](hover::...)` syntax just fine? We could use them and avoid parsing DoD syntax ourselves?

What I'm suggesting might be tricky and take a lot of time, so going ahead with the existing implementation is definitely an option.

2022-07-13 13:08 UTC, ikesau commented on clientUtils/Util.ts
> +export function checkIsChildOfClass(
This can be removed

2022-07-13 13:08 UTC, ikesau commented on db/migration/1653584089031-DetailsOnDemand.ts
> +export class DetailsOnDemand1653584089031 implements MigrationInterface {
Not sure why this is in here. I think git's confused.

2022-07-13 13:10 UTC, ikesau commented on grapher/detailsOnDemand/detailsOnDemand.tsx
> +export const globalDetailsOnDemand = new DetailsOnDemand()
Not sure about this pattern, was just trying to set something up for if/when we start having DoDs in articles.

It also makes it much easier for the MarkdownTextWrap to hook into

2022-07-13 13:12 UTC, ikesau commented on grapher/downloadTab/DownloadTab.tsx
> +                                    this.isReady = false
this line makes the grapher loading spinner re-appear for 500ms while the images re-render. 

If we don't have it, then instead you see the static export thumbnails flash and change their aspect ratio. I'm not sure which is better.

2022-07-13 13:13 UTC, ikesau commented on grapher/text/MarkdownTextWrap.stories.tsx
> +import React, { createRef } from "react"
and more. can be ignored

2022-07-18 01:26 UTC, merged