migration(variables,datasets): add shortName and version to variables and datasets tables
owid/owid-grapher pull request #1566
Opened 2022-07-28 12:45 UTC by Marigold

2022-07-29 09:08 UTC, larsyencken requested changes
The constraints are too aggressive, since short names can be reused in different namespaces. I think it should be:

- On `variables`: each `(short_name, datasetId)` should be unique, ignoring nulls
- On `datasets`: each `(short_name, version, namespace)` should be unique, ignoring nulls

2022-07-29 09:08 UTC, larsyencken commented on db/migration/1659011799966-AddShortNameAndVersionToDatasets.ts
> +            ALTER TABLE datasets ADD UNIQUE (shortName);
```suggestion
            ALTER TABLE datasets ADD CONSTRAINT unique_short_name_version_namespace UNIQUE (shortName, version, namespace);
```

2022-07-29 09:08 UTC, larsyencken commented on db/migration/1659011799966-AddShortNameAndVersionToDatasets.ts
> +    public async down(queryRunner: QueryRunner): Promise<void> {
```suggestion
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE datasets DROP INDEX unique_short_name_version_namespace;
        `)
```

2022-07-29 09:08 UTC, larsyencken commented on db/migration/1659011791860-AddShortNameToVariables.ts
> +            ALTER TABLE variables ADD UNIQUE (shortName);
```suggestion
            ALTER TABLE variables ADD CONSTRAINT unique_short_name_per_dataset (shortName, datasetId);
```

2022-07-29 09:08 UTC, larsyencken commented on db/migration/1659011791860-AddShortNameToVariables.ts
> +        await queryRunner.query(`
```suggestion
        await queryRunner.query(`
            ALTER TABLE variables
            DROP INDEX unique_short_name_per_dataset
        `)
        await queryRunner.query(`
```

2022-08-03 08:36 UTC, Marigold commented
Added `shortName` and `version` update for existing ETL datasets.

2022-08-03 09:17 UTC, larsyencken approved these changes
Looks good to go! Great that you included the data changes we want in the migration too.

2022-08-03 11:49 UTC, merged