Run refresh scripts in containers
owid/owid-grapher pull request #1638
Opened 2022-09-07 09:33 UTC by mlbrgl

The make refresh / refresh.wp commands run mysql on the host, rather than in containers. This adds an extra requirement  for local setups.

This PR runs the refresh script in containers instead.

It also fixes regression in tasks.json introduced in https://github.com/owid/owid-grapher/commit/bc3a688cf757f3541660aa3e74d9f873c89b2d65

Why use docker-compose.full.yml in make refresh? (vs docker-compose.grapher.yml)

This is to silence the complaints about orphan containers if your setup is based on docker-compose.full and you're running a task with docker-compose.grapher (which has less containers and are then seen as orphans). 

My assumption is that the run command doesn't spin up all containers (only the one concerned by the command), and so running it with a docker-compose.full config has no impact on docker-compose.grapher setups. No additional containers should be created from the docker-compose.full config.

2022-09-09 12:37 UTC, larsyencken requested changes
Hmm... now it doesn't work on the command-line for me. For `make refresh`, I get:

```
==> Downloading chart data
./devTools/docker/download-grapher-mysql.sh
Downloading live Grapher metadata database (owid_metadata)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 46.0M  100 46.0M    0     0  12.4M      0  0:00:03  0:00:03 --:--:-- 12.4M
Downloading live Grapher chartdata database (owid_chartdata)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  228M  100  228M    0     0  17.1M      0  0:00:13  0:00:13 --:--:-- 17.5M
==> Updating grapher database
docker compose -f docker-compose.full.yml run --rm db-load-data /app/refresh-grapher-data.sh
[+] Running 1/1
 ⠿ Container owid-grapher_db_1  Recreated                                                      2.7s
[+] Running 4/4
 ⠿ Container owid-grapher-db-1                           Star...                               0.3s
 ⠿ Container owid-grapher_wordpress-install_1            Started                               0.4s
 ⠿ Container owid-grapher_db-load-data_1                 Started                               0.4s
 ⠿ Container owid-grapher_wordpress-owid-plugin-build_1  Started                               0.3s
[Entrypoint] MySQL Docker Image 8.0.28-1.2.7-server
==> Refreshing grapher database
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'db:3306' (111)
make: *** [refresh] Error 1
```

I'm sympathetic to the idea that it's nice to remove `mysql` as a dependency on the host system, although since I need and use command-line mysql anyway, and it's required to be installed anyway for our data work (for Python packages), it seems low prio to remove.

Is it currently broken in VSCode tasks?

2022-09-09 12:37 UTC, larsyencken commented on devTools/docker/refresh-grapher-data.sh
> +        # import_db $DATA_FOLDER/owid_chartdata.sql.gz
Assuming this shouldn't be commented out, and it was just for testing.

2022-09-30 15:29 UTC, mlbrgl commented
After a recent conversation with @larsyencken, we agreed to drop this in favour of a more flexible `make refresh` command, that would allow a more selective update of the grapher DB by making chart data updates optional.

@larsyencken you can close this PR if you're tracking the task mentioned above somewhere else

2022-10-03 13:30 UTC, larsyencken commented
Superseded by https://github.com/owid/owid-grapher/pull/1688

2022-10-03 13:30 UTC, closed without merging