feat(grapher): add option to hide scatter labels
owid/owid-grapher pull request #1966
Opened 2023-03-01 11:09 UTC by sophiamersmann

Adds an option to hide entity names in scatter plots, as requested in #1550.

Issue #1550 states that this option should also work in explorers - that piece is missing atm. Daniel suggested to come back to this in a few days when I'm a bit more familiar with the codebase and focus on Grapher for now.

2023-03-02 14:41 UTC, danyx23 requested changes
Hi @sophiamersmann, this already looks really good - really cool that you are fixing issues already!

I have two minor requests:
* Hiding the labels works well in the default case but if you hover over the color legend then all the labels are visible again. I think that for cases like the GPU chart this is pretty distracting so I would replicate the behaviour of the normal case when hovering over color legend labels.
* I wonder if it would make sense to move the toggle in the admin into the existing Point Labels section and maybe make the label a bit more self-explanatory. E.g. what about "Hide point labels (except when hovering)"?

2023-03-02 17:15 UTC, sophiamersmann commented
I wasn't sure how to differentiate between "This label is hovered over by a mouse" and "This label is in the hover state because the resp. legend item is hovered over". To differentiate I simply check how many labels are hovered over at the moment – if only one, then the interaction happened probably on the data point itself, hence show the label, otherwise don't show the label. One caveat here is that if a color group contains a single data point only, then the label will show up when hovering over the legend entry (though it shouldn't). I thought that'd be okay though because a single label can't overlap with anything...

2023-03-03 09:09 UTC, marcelgerber commented
> I was wondering, btw, what the "year/x/y" selection in the "Point Labels" section does?

Ah, interesting question, it also took me some time to figure it out.
It's only relevant when in "connected scatter" mode, which only a small subset of our scatter plots are. (There is also an UI element to switch to connected scatter mode, but it is possibly OWID's best-kept secret and totally undiscoverable 🤫 ).

Take this chart for example: https://ourworldindata.org/grapher/nitrogen-output-vs-nitrogen-input-to-agriculture (it's a bit of a mess, but ignore that for now).
If you now hover over a country, you'll see that the line that appears is annotated with years in this case.
That's because "Point labels" is set to "year" in this case - if it were set to "y", then the y variable value would show instead.

2023-03-03 09:37 UTC, marcelgerber approved these changes
Good work!
This works well, and the decision to only show hover labels when the series contains one entity makes sense too (and is also cool for the rare case when the user hovers a single-entity series on the right).

LGTM!

2023-03-03 11:57 UTC, merged