:tada: Rich text in gdoc footnotes
owid/owid-grapher pull request #2293
Opened 2023-06-06 17:54 UTC by ikesau

A request that came from @bastianherre that was trivial to fix.

Demo:

https://github.com/owid/owid-grapher/assets/11844404/769a4a28-c1e4-4c1b-8b9c-a3e80bd6590d

Testing Archie:

```
[+body]

This claim needs an ultra reference {ref} This article draws on several very helpful other articles summarizing and reviewing some of the datasets, as well as the datasets’ codebooks and descriptions:
Eisner, Manuel. 2003. [Long-Term Historical Trends in Violent Crime](https://www.journals.uchicago.edu/doi/abs/10.1086/652229). Crime and Justice 30: 83-142.
Eisner, Manuel. 2008. [Modernity Strikes Back? A Historical Perspective on the Latest Increase in Interpersonal Violence (1960-1990)](https://www.ijcv.org/index.php/ijcv/article/view/2769). International Journal of Conflict and Violence 2(20: 288-316.
Eisner, Manuel. 2014. [From Swords to Words: Does Macro-Level Change in Self-Control Predict Long-Term Variation in Levels of Homicide?](https://www.journals.uchicago.edu/doi/10.1086/677662) Crime and Justice 43: 65-134.
GBD 2019 Diseases and Injuries Collaborators. [Global burden of 369 diseases and injuries in 204 countries and territories, 1990-2019: a systematic analysis for the Global Burden of Disease Study 2019](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)30925-9/fulltext). Lancet 396: 1204-1222.
GBD 2019 Diseases and Injuries Collaborators. [Global burden of 369 diseases and injuries in 204 countries and territories, 1990-2019: a systematic analysis for the Global Burden of Disease Study 2019](https://www.thelancet.com/cms/10.1016/S0140-6736(20)30925-9/attachment/7709ecbd-5dbc-4da6-93b2-3fd0bedc16cc/mmc1.pdf). Lancet 396: Supplementary appendix 1.
Kanis, Stefan, Steven Messner, Manuel Eisner, and Wilhelm Heitmeyer. 2017. [A Cautionary Note about the Use of Estimated Homicide Data for Cross-National Research](https://journals.sagepub.com/doi/abs/10.1177/1088767917715670). Homicide Studies 21(4): 312-324.
Rogers, Meghan, and WIlliam Pridemore. 2023. [A Review and Analysis of the Impact of Homicide Measurement on Cross-National Research](https://www.annualreviews.org/doi/abs/10.1146/annurev-criminol-030521-102909). Annual Review of Criminology 6: 447-470.
United Nations Office on Drugs and Crime. 2019. [Methodological Annex to The Global Study on Homicide 2019](https://www.unodc.org/documents/data-and-analysis/gsh/Meth_Annex_GHS.pdf).
United Nations Office on Drugs and Crime. 2022. UNODC Research Data Portal. [Intentional Homicides Metadata information](https://dataunodc.un.org/sites/dataunodc.un.org/files/metadata_intentional_homicide.pdf).
World Health Organization. 2020. [WHO methods and data sources for country-level causes of death 2000-2019](https://www.who.int/docs/default-source/gho-documents/global-health-estimates/ghe2019_cod_methods.pdf).
World Health Organization. nd. [Estimates of number of homicides](https://www.who.int/data/gho/indicator-metadata-registry/imr-details/4464). {/ref}

This one needs a normal reference {ref}Don’t mind me!{/ref}

This one needs a long reference so that the footnotes column looks harmonious {ref}Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean odio neque, feugiat gravida leo vitae, hendrerit sodales ligula. Curabitur pharetra ligula dolor, sit amet efficitur risus scelerisque a. Cras vitae urna vitae enim euismod viverra. Nullam sit amet pharetra lacus. Suspendisse vulputate sapien commodo, finibus felis sit amet, bibendum orci. Suspendisse ornare, elit sit amet iaculis luctus, tortor mauris sodales tortor, sit amet cursus enim est non elit. Aenean lobortis lorem ut odio vulputate, id accumsan risus convallis. Sed vitae ullamcorper diam. Curabitur condimentum lacus sit amet ultrices mattis. Nulla facilisi. Morbi elit mauris, sagittis sed metus at, rhoncus sollicitudin metus. Donec magna ex, tincidunt eu facilisis convallis, lobortis et velit. Pellentesque dignissim libero a justo commodo, at luctus mi facilisis. Donec quis ex pharetra, molestie neque non, faucibus velit.
Nulla facilisi. Donec mattis, tortor ut efficitur laoreet, orci metus condimentum nisl, at dictum ligula nisi vehicula sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lorem ac elit faucibus pulvinar. Integer feugiat libero mi, ut fringilla neque condimentum vel. Phasellus varius pellentesque ultrices. Praesent ac nibh dictum, scelerisque leo eu, tempus urna. Nullam ullamcorper nunc justo, ac vulputate odio euismod nec. Pellentesque porta nec erat dictum tincidunt. In et euismod sapien. Mauris et ligula posuere, maximus nibh ut, ornare tellus. Etiam eleifend augue sem, interdum congue tortor accumsan non. Maecenas sit amet congue tellus. Duis vitae commodo libero. Suspendisse semper erat vel leo imperdiet dictum.
Vivamus tellus purus, iaculis a viverra finibus, pellentesque vel nisi. Duis volutpat risus neque, et convallis odio accumsan nec. Nulla sollicitudin nibh viverra, pulvinar tortor eu, euismod diam. Aenean laoreet lacus lacus, ut commodo odio congue non. Donec erat arcu, varius sit amet nisl placerat, tristique bibendum turpis. Cras sit amet dolor sodales, efficitur lorem vitae, pellentesque nisi. Morbi vel elit sed justo commodo pulvinar. Vestibulum suscipit magna nulla, in tincidunt nibh lacinia maximus. Mauris id magna sagittis, posuere risus lobortis, malesuada odio. Aliquam vel nisl posuere, fringilla neque mattis, eleifend urna. Phasellus ac sollicitudin magna, ut sodales lectus. Ut ut diam nulla.
{/ref}

[]
```

2023-06-06 20:10 UTC, ikesau commented
todo: this will require a migration as well.

2023-06-07 10:18 UTC, danyx23 reviewed
This makes footnotes almost too powerful but I think in practice authors will not go totally crazy (... 🤞)

One log statement made it through and as you said the migration is still missing. Do you want to ping me again once that is added?

2023-06-07 10:18 UTC, danyx23 commented on db/model/Gdoc/archieToEnriched.ts
> +    )
Superfluous comment

2023-06-12 11:31 UTC, danyx23 commented
@ikesau I think it might be better to deal with two kinds of refs - old style refs (everything between the ref tags becomes the footnote) and single word refs which are treated as ids of items in the ref block. I think this would make for a nicer experience for existing content (there might be quite a few posts that use the old style that are not yet publisehd) and also it would be useful to keep the migration working. Do you see a big issue in doing this?

2023-06-13 15:25 UTC, ikesau commented
@danyx23 done!

I hash the contents of each inline ref so that we can potentially re-use footnote numbers if the contents is identical. This also allows us to mostly reuse the same logic that I've written for the ID-based ref system.

It's quite a big function though so let me know if you want a quick call to talk it through. 👍

2023-06-15 18:06 UTC, danyx23 requested changes
Nice! This is getting very close. I found two cases of unexpected behaviour: 
* Inline refs lead to a document error entry about the hash not being defined (it works but the error is shown in the document sidepanel)
* When you define refs but then misspell the reference id at the point of use then you get a document error entry but also the footnote indicator renders, does not give you an on-hover footnote but there is an endnote entry that seems to reference the first ref (or the ref at the corresponding index?). See this example doc: https://docs.google.com/document/d/1ImYJfRy_cXvsRTsI1lYgXmh1vG1mMtvnXWrGuDtrGLw/edit

2023-06-15 21:35 UTC, ikesau commented
Oops! Very silly oversight on that inline ref error message. I've refactored slightly to enrich all the refs at the same time, which fixes the issue (and improves the readability of the code, imo)

I don't think it's worth adding the necessary complexity to improve how we render broken refs. 

If you misspell the ID of the ref, it's going to break and we won't let you publish the document. That seems fine to me.

2023-06-15 21:41 UTC, danyx23 commented
Fair enough about the misspelling. I haven't checked it after your last changes but if you feel confident then feel free to go ahead and merge and tell authors about it :)

2023-06-16 16:08 UTC, merged