🐛 pre-fetch linkedCharts before baking
owid/owid-grapher pull request #2361
Opened 2023-06-22 23:33 UTC by ikesau

Found a pretty glaring oversight in the Gdoc baking process - we weren't including `linkedCharts`, which are needed to resolve any URLs / metadata to charts/explorers within a Gdoc.

It's a slightly more involved process because we need to resolve redirects first.

e.g. if a gdoc has a prominent link:

```
{.prominent-link}
url: https://ourworldindata.org/grapher/some-slug
{}
```
We use that slug to get the title and thumbnail for the prominent link.

If we update that slug, a redirect is created and we have to then resolve that redirect first before we can fetch the correct metadata.

2023-06-22 23:41 UTC, ikesau commented on packages/@ourworldindata/utils/src/owidTypes.ts
> -    path: string
This implementation was actually flat out broken. I don't know why I went with such ambiguous names the first time 😵

2023-06-22 23:43 UTC, ikesau commented on baker/SiteBaker.tsx
> +            await publishedGdoc.loadRelatedCharts()
This is from #2326 , where I made this commit initially but then cherry-picked over to a new branch to isolate it for a PR.

It fixes a bug so it's fine to merge it here too.

2023-06-24 14:00 UTC, marcelgerber requested changes
Yeah makes sense overall!
But found a few cases where this will still go wrong atm 🤐

2023-06-26 17:03 UTC, marcelgerber approved these changes

2023-06-26 17:51 UTC, merged