feat(gdocs): breadcrumbs
owid/owid-grapher pull request #2375
Opened 2023-06-27 14:18 UTC by marcelgerber

2023-06-27 14:18 UTC, marcelgerber commented
Current dependencies on/for this PR:
* master
  * **PR #2367** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2367" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2375** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2375" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2375?utm_source=stack-comment).

2023-07-04 16:44 UTC, marcelgerber commented
The admin editing flow for this is a bit subpar at the moment, since you don't get any live preview of what the breadcrumbs will look like, sadly.

However, it at least reloads after you click "Done" and "Save draft".

It might make sense to add a short hint for that behaviour?

https://github.com/owid/owid-grapher/assets/2641501/b7321b3b-3076-4e17-acb9-893bc73dfbe6

2023-07-04 16:54 UTC, marcelgerber commented on adminSiteClient/GdocsBreadcrumbsInput.tsx
> +    errors,
Open question: Should I be using `errors` somewhere? What kind of validation would be useful?

2023-07-12 01:02 UTC, ikesau requested changes
Really nice! This could have been a very scope-crept feature and I think you carved it down nicely.

My only comments are a few little UI bugs.

I'm a little weary of introducing absolute links to our Gdoc metadata. Thus far we'd been doing everything with Gdoc IDs which allows us to automate all redirects and validate nicely.

Pasting gdoc IDs into the admin wouldn't be very nice because you wouldn't get an inline preview, and I'm not going to ask you to redo this to work with archie either 😛 

But maybe we can keep in mind that it might be more idiomatic/nicer to write these in Archie if we revisit breadcrumbs in the future.

2023-07-12 11:40 UTC, marcelgerber commented on adminSiteClient/GdocsBreadcrumbsInput.tsx
> +                    <Input
Wait what's weird here?
I can see how it's a bit weird UI-wise, but yeah, that's actually how it's meant to look:

The last breadcrumb (it's basically a short form of the current page title, like "Goal 7: Affordable and clean energy") and hence, its URL field is disabled.

2023-07-12 12:30 UTC, marcelgerber commented on adminSiteClient/GdocsPreviewPage.tsx
> +                    key={`${currentGdoc.revisionId}-${originalGdoc?.updatedAt}`}
Well spotted! Just fixed this one.

2023-07-12 13:00 UTC, marcelgerber commented on adminSiteClient/GdocsBreadcrumbsInput.tsx
> +                    <Input
Oh, interesting. I guess you're doing the UX testing here ;)

Yeah, I now see your point, I'll change it so new breadcrumbs are added at the front instead, and hence the disabled field doesn't move around.

2023-07-12 15:10 UTC, ikesau approved these changes

2023-07-12 15:18 UTC, merged