Self-hosted Lato & Playfair Display fonts
owid/owid-grapher pull request #2518
Opened 2023-08-07 20:32 UTC by samizdatco

This PR removes the dependency on Google Fonts for our two main typefaces: Lato and Playfair Display. The font files are now served as `woff2` files in the `/fonts` directory (which can be found in the repo under `public/fonts`. The css file served at `/fonts.css` defines `@font-face` rules pointing to the self-hosted files and can be referenced from baked SVGs so they can render correctly even if the user doesn't have local copies of the fonts installed.

2023-08-09 14:17 UTC, marcelgerber requested changes
Nice work!

Sadly, I've got some concerns over the file sizes; but yeah there are some improvements that we can definitely make to get closer to our targets.

Also, it would be nice if you could include a README in the `fonts` folder which contains URLs to these fonts and where you got them; I assume you got Lato from l[atofonts.com](https://www.latofonts.com/lato-free-fonts/), but for Playfair I can't find an "authoritative" URL anywhere.

2023-08-09 14:17 UTC, marcelgerber commented on public/fonts.css
One big problem I'm seeing here, in general, is that our font files are _massively larger_ than what Google Fonts is delivering.

<table>
<tr>
 <th>Font
 <th>Google Fonts size
 <th>Our size
<tr>
 <td>Lato Regular
 <td>14 KB (well, the Latin subvariant)
 <td>183 KB
<tr>
 <td>Lato Latin Regular (if we were using that)
 <td>14 KB
 <td>44 KB
<tr>
 <td>Playfair Display Regular
 <td>36 KB
 <td>66 KB
</table>

Note also that we're of course using more than a single font file, and in actuality:
- The 5 webfonts loaded on https://ourworldindata.org/poverty are 93 KB combined
- The 8 webfonts loaded on https://staging-owid.netlify.app/poverty are 1.2 MB combined!

I think this kind of increase is unacceptable, sadly.

Both Google Fonts and we are using `woff2` files already. There are a few ways how we could bring these down quite a bit.

Foremost is using Lato Latin over Lato, since Latin is roughly one-fourth of the size. There are multiple ways to do this:
- (easy) Only use Lato Latin. There may be a few characters here and there that look a bit worse, but since we're _almost_ exclusively using characters from the Latin variant, it's not a lot.
- (harder) Use the [`unicode-range`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range) field to specify that the browser should load Lato Latin for the range of Latin characters, and full Lato for other characters.
I didn't check this, but since I assume that non-Latin characters are only contained in very few pages, and then probably also only need a single font weight, that would still be a huge improvement.
- (also hard) We could subset the font ourselves using a tool like [glyphhanger](https://github.com/zachleat/glyphhanger), and pick out the characters that may come up but disregard others to reduce size.

2023-08-10 18:36 UTC, samizdatco commented on public/fonts.css
The `fonts.css` file now includes `unicode-range` definitions for both the latin and full versions of Lato. The ranges for the latin subset include all the glyphs in the font whereas the full version's range only includes codepoints that are *not* in the latin subset.

2023-08-14 00:11 UTC, samizdatco commented
I added a script & makefile to `devTools/fonts` to fetch the source font files, convert them to woff2s and generate the css file. It installs its dependencies (and stores its downloads/tempfiles) in `devTools/fonts/.env` so they'll be ignored by git. Take a look at the [readme](https://github.com/owid/owid-grapher/blob/cfbb2ce6160edd4a9cccb246f9d9346842548707/devTools/fonts/README.md) for details.

2023-08-14 18:07 UTC, samizdatco commented on packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
> +    bakedGrapherURL?: string
oops

2023-08-16 13:38 UTC, marcelgerber approved these changes
Finally! Nice, this looks good now, thank you for your hard work!

2023-08-16 17:19 UTC, samizdatco commented
Fixes #1910

Leaving the SVG 'embedding' part for later…

2023-08-16 17:19 UTC, merged