Remove Gdoc Preview autoupdating, fix lightning publishing
owid/owid-grapher pull request #2766
Opened 2023-10-13 14:52 UTC by ikesau

Autoupdating was causing lots of headaches when multiple clients were previewing the same document. The effort in fixing that class of issue seems to outweigh the marginal benefit of autoupdating, so I'm removing the autoupdating functionality altogether.

I also noticed that lightning updates hadn't been working properly for ages, so I've updated that code to fix the thing that was breaking it (Date comparisons) and made the declaration of light props more explicit and tied to our type validation so that it'll be harder to miss in the future.

2023-10-16 12:55 UTC, mlbrgl requested changes

2023-10-16 12:58 UTC, mlbrgl reviewed
Nice refactoring on the lightning update! It is much more future-proof now that is tied to a type 👍

2023-10-18 22:03 UTC, ikesau commented on adminSiteClient/gdocsDeploy.ts
> +    )
Nice catch! Those variables being swapped was just a goof, definitely not intentional. But I'm glad it prompted you pointing out this potential footgun in either case.

I've updated the `GdocsStore.update` method from the preview page to omit the tags property in the JSON it posts. This means that the tags in the DB won't get changed in any way from publishing a gdoc.

I think this means that technically we should trigger a bake whenever a Gdoc's tags are updated, but we don't do that for charts either, and I think we could try it out this way first (with manual+incidental bake triggers) and see if that works well enough.

2023-10-24 12:01 UTC, mlbrgl commented on adminSiteClient/gdocsDeploy.ts
> +    )
yes, I agree. 

Tested and both issues are gone, nice!

2023-10-24 12:01 UTC, mlbrgl approved these changes

2023-10-24 20:49 UTC, merged