data-page-better-date-formats-processing-level
owid/owid-grapher pull request #2801
Opened 2023-10-19 10:03 UTC by danyx23

2023-10-23 12:48 UTC, sophiamersmann requested changes

2023-10-23 12:50 UTC, sophiamersmann commented
Looks good! I only have a couple of very minor comments. Formatting dates nicely makes a surprisingly big difference :)

2023-10-24 09:07 UTC, danyx23 commented on site/DataPageV2Content.tsx
> +    const dateRangeRegex = /^\s*(?<start>(-)?\d+)\s*(-|–)\s*(?<end>(-)?\d+)\s*$/
I really like named groups, very nice that this introduced them to you :)

2023-10-24 09:19 UTC, danyx23 commented on site/DataPageV2Content.tsx
> +    const lastUpdated = dayjs(datapageData.lastUpdated, ["YYYY", "YYYY-MM-DD"])
I just updated this again in the citations PR which I think resolves this particular issue - but in general, there are 3 relevant dates IMHO: when was the data last updated, when did we last process it and when did the user access it (today). When you look at the citations PR and this is still unclear or confusing then please flag it again there!

2023-10-24 09:19 UTC, danyx23 commented on site/DataPageV2Content.tsx
> +                                            with{" "}
I fixed this in the follow up citations PR

2023-10-24 09:23 UTC, sophiamersmann commented on site/DataPageV2Content.tsx
> +    const lastUpdated = dayjs(datapageData.lastUpdated, ["YYYY", "YYYY-MM-DD"])
ahh, that makes sense 💡

2023-10-24 09:28 UTC, danyx23 commented on site/DataPageV2Content.tsx
>      const citationLong = `${citationShort}. ${datapageData.title}. ${originsLong}, ${processedAdapted} by Our World In Data. Retrieved ${dateAccessed} from ${urlAccessed}`
I fixed this one as well in the follow up PR just now. Thanks for raising this!

2023-10-24 16:29 UTC, merged

2023-10-24 16:29 UTC, danyx23 commented
### Merge activity

* **Oct 24, 12:29 PM**: @danyx23 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2801).