Sources modal: Multiple indicators
owid/owid-grapher pull request #2886
Opened 2023-11-02 14:35 UTC by sophiamersmann

2023-11-02 14:35 UTC, sophiamersmann commented
Current dependencies on/for this PR:
* master
  * **PR #2794** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2794" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2853** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2853" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #2877** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2877" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #2886** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2886" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #2795** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2795" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2886?utm_source=stack-comment).

2023-11-07 10:44 UTC, sophiamersmann commented on packages/@ourworldindata/core-table/src/CoreTableColumns.ts
> +        return this.display?.name || this.name || ""
this is why the svg tester comes back with a few updated charts

2023-11-17 18:39 UTC, danyx23 requested changes
Looks good! I have a few remarks about the wording in slack and I think we should only show multiple indicator tabs if there is a difference between the content we show for each one (i.e. if all are the same we don't show any tabs; if there are differences it is fine to show all indicators, even if most are the same - i.e. no need to de-duplicate further; but all sources being the same is a common case due to our need to split multi-dimensional indicators and we should not confuse our users with this if we don't have to)

2023-11-17 18:39 UTC, danyx23 commented on packages/@ourworldindata/components/src/Tabs/Tabs.tsx
> +    function getNextIndex(eventKey: string): number {
❤️

2023-11-27 11:27 UTC, merged