:hammer: (db) migrate Dataset and Source to knex
owid/owid-grapher pull request #3131
Opened 2024-01-24 15:40 UTC by sophiamersmann

- Makes the `Dataset` and `Source` TypeORM classes obsolete by switching db access to knex
- This PR does not do any clean-up, e.g. SQL queries in the router files are not moved, although they ultimately should live in the `db` folder

- I added two helper functions that can be used as drop-in replacements for `queryMysql` and `mysqlFirst` that are often used in our codebase, `knexRaw` and `knexRawFirst` (both live in `db.ts`)

- Routes that I could easily test are tested, but not all of the code is!

@danyx23 let me know if this is how you imagined it, or if I should do anything differently.

@coderabbitai ignore

2024-01-24 15:40 UTC, sophiamersmann commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3131?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #3054** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3054?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #3056** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3056?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #3064** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3064?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #3131** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3131?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
        * **PR #3074** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3074?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/3131?utm_source=stack-comment).

2024-01-24 15:55 UTC, sophiamersmann commented on adminSiteServer/apiRouter.ts
> +                oldDatasetName: dataset.name!,
The TypeORM code just assumed that a dataset `name` was given. That's why I felt it was safe to sometimes ignore a possible undefined value via Typescript's `!`. Let me know if you prefer for this to be handled properly.

2024-01-24 15:57 UTC, sophiamersmann commented on adminSiteServer/apiRouter.ts
> +    const source = await db.knexRawFirst<Record<string, any>>(
When it wasn't particularly important, I didn't use specific types. Let me know if you prefer to have strict types everywhere.

2024-01-26 12:01 UTC, danyx23 requested changes
Thanks a lot for test driving the knex approach! This looks very good overall. There are two things that I would change on the db-types PR learning from this and two things I'd ask you to change.

The two changs I'd like to see to this PR is:
- not make the knex instance optional in the knexRaw and knexRawFirst helper functions
- and to wrap all API functions we touch in a transaction scope even if we only read data as we go through them. The reasoning here is that we want reads to be consistent and it's probably better to just implement a standard pattern everywhere rather than having to evaluate if it is necessary each time.

The two things I'll change on the other PR are:
- bump the knex version so that we can create readyOnly transactions which are a bit more performant than generic ones
- add a migration to make name on datasets mandatory rather than nullable

2024-01-26 12:01 UTC, danyx23 requested changes
Thanks a lot for test driving the knex approach! This looks very good overall. There are two things that I would change on the db-types PR learning from this and two things I'd ask you to change.

The two changs I'd like to see to this PR is:
- not make the knex instance optional in the knexRaw and knexRawFirst helper functions
- and to wrap all API functions we touch in a transaction scope even if we only read data as we go through them. The reasoning here is that we want reads to be consistent and it's probably better to just implement a standard pattern everywhere rather than having to evaluate if it is necessary each time.

The two things I'll change on the other PR are:
- bump the knex version so that we can create readyOnly transactions which are a bit more performant than generic ones
- add a migration to make name on datasets mandatory rather than nullable

2024-02-27 15:01 UTC, sophiamersmann reviewed
Good to go I think!

Before the `name` field was made non-nullable in the db, I added a check to make sure a dataset `name` is given. We could get rid of that now :)

2024-02-27 15:59 UTC, merged