Add redirects table and migration script
owid/owid-grapher pull request #3185
Opened 2024-02-09 11:42 UTC by mlbrgl

wip: add redirects table migration

feat: add Wordpress redirects sync script

2024-02-09 11:42 UTC, mlbrgl commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3185?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #3165** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3165?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #3166** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3166?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #3176** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3176?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #3179** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3179?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #3182** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3182?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #3185** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3185?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/3185?utm_source=stack-comment).

2024-02-13 20:28 UTC, danyx23 reviewed
Very nice to finally pull this into our DB :)

I think it would be good to do a bit more cleanup in the sync script:
- remove trailing slashes in source
- remove trailing slashes in target unless it is the root url (/)
- get rid of chains. We currently have 28 redirects where the target of one is the source of another (i.e. A.target == B.source - see query below). I think it would be nice to resolve these to the final target before storing them in our DB

To see the chains, this query is useful:
```sql
select
	hop1.source as initialSource,
	hop1.target as intermediateTarget,
	hop2.target as finalTarget,
	hop3.target as veryFinalTarget
from
	redirects hop1
inner join redirects hop2 on
	hop2.source = hop1.target
left join redirects hop3 on
	hop2.target = hop3.source
```

2024-02-13 20:29 UTC, danyx23 requested changes
see above

2024-02-16 08:59 UTC, mlbrgl commented
@danyx23 

> remove trailing slashes in source
remove trailing slashes in target unless it is the root url (/)

✅ (see code comments for further edge cases)

> get rid of chains. We currently have 28 redirects where the target of one is the source of another (i.e. A.target == B.source - see query below). I think it would be nice to resolve these to the final target before storing them in our DB

✅ I adapted and reused the internal resolver logic for this

2024-02-19 08:30 UTC, danyx23 approved these changes
Nice, looks good! Arguable existingRedirectsFromDb should be a set but the runtime difference is probably negligible :)

2024-02-19 09:11 UTC, mlbrgl commented
@danyx23 yes at that scale any kind of optimization probably doesn't change much, especially given that we won't be running this script more than a handful of times.

Out of curiosity though, do you mean doing something like what you did there?
https://github.com/owid/owid-grapher/blob/2785a248347703df43ac4e3b255cd795c97d4fde/db/syncPostsToGrapher.ts#L219-L229

2024-02-19 17:02 UTC, mlbrgl commented
### Merge activity

* **Feb 19, 12:02 PM EST**: @mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/3185).

2024-02-19 17:10 UTC, merged