garden: remove unneeded DB column
owid/owid-grapher pull request #3717
Opened 2024-06-18 10:13 UTC by toni-sharpe

Fixes #3169

2024-07-02 08:34 UTC, larsyencken requested changes
Thanks for this gardening work Toni! 

Rather than put this in the initial schema for everything, can you please add it as a new migration?

You can find instructions for that here: https://github.com/owid/owid-grapher/blob/master/db/readme.md#creating-a-migration

2024-07-03 15:53 UTC, toni-sharpe commented
@larsyencken no problem, should get a look before Monday. Migrations as well, I should have got that!

2024-07-03 20:39 UTC, toni-sharpe commented
@larsyencken I just pushed this up, having a spot of bother locally so thought it best to keep things moving and push blind, I'll look at what my issues are and should be able to report this work as "tested locally" then. In the meantime, someone might merge it.

2024-07-10 08:03 UTC, larsyencken commented on db/migration/1720038601815-RemoveEntitiesDisplayName.ts
> +                displayName`
```suggestion
                displayName varchar(255) COLLATE utf8mb4_0900_as_cs NOT NULL`
```

2024-07-10 08:22 UTC, merged

2024-07-10 08:24 UTC, larsyencken commented
Tidied up and merged now, thanks Toni!