Chang DoDs to be spans instead of links
owid/owid-grapher pull request #3815
Opened 2024-07-26 07:53 UTC by rakyi

They don't link to anything and should not be rendered as links in HTML for cases like an Atom feed. See [Slack discussion](https://owid.slack.com/archives/CQQUA2C2U/p1721898655529639).

2024-07-26 07:55 UTC, rakyi commented on packages/@ourworldindata/grapher/src/core/grapher.scss
> -    a.dod-span {
We no longer need to override the styles for links.

2024-07-29 13:33 UTC, marcelgerber requested changes
Hi! For whatever reason, neither the styles nor the event handler applies in admin.
See [this chart](http://staging-site-dod-span/admin/charts/5942/edit), for example, where "newborns" in the subtitle should be DoD-ified.

2024-07-29 13:35 UTC, marcelgerber commented
Ah, right: It's probably enough to make sure the DoD styles are explicitly included in admin.
Just noticed the `.dod-span span { pointer-events: none }` rule, that should just about do it :)

2024-07-30 13:54 UTC, rakyi commented on packages/@ourworldindata/grapher/src/core/grapher.scss
> -    a.dod-span {
As Marcel pointed out, we still need to add the styles to Grapher. Added a mixin for this.

2024-07-30 13:54 UTC, rakyi commented
Did it with a mixin. Does that work?

2024-07-30 14:04 UTC, marcelgerber approved these changes
Yes that's great.

2024-07-30 14:04 UTC, marcelgerber commented on packages/@ourworldindata/components/src/styles/mixins.scss
> +    border-bottom: 1px dotted #1d3d63;
Can we replace this with the color name?
```suggestion
    border-bottom: 1px dotted $blue-90;
```

2024-07-30 14:19 UTC, merged