3817
owid/owid-grapher pull request #3907
Opened 2024-08-28 05:31 UTC by toni-sharpe

## Description

There was a bit more than just changing the width:

* changed `400px` to `80vw` which is more responsive anyway, but was also needed to catch longer rows with dates
* `white-space: nowrap` kept the date from breaking line
* combining the swatch colour with name avoided the problem with `<table />` guessing at widths which made a huge gap between swatch and name

Fixes #3817 
Fixes #2714 (confident, not tested)

## Screen-shot results

<img width="700" alt="Screenshot 2024-08-28 at 07 04 20" src="https://github.com/user-attachments/assets/98e21bdf-c3ba-48eb-8c24-1a4e3f234468">
<img width="700" alt="Screenshot 2024-08-28 at 07 04 27" src="https://github.com/user-attachments/assets/bd5765d9-3af5-4e6b-854b-319373368cd1">

## A few more

<details><summary>Open for: different dates, different discrete bar charts</summary>

### Different dates

<img width="774" alt="Screenshot 2024-08-28 at 07 10 59" src="https://github.com/user-attachments/assets/fa59f0f4-c300-4114-9bdd-04b9a581bc39">
<img width="774" alt="Screenshot 2024-08-28 at 07 11 08" src="https://github.com/user-attachments/assets/074bca22-d8f6-4652-917c-7356037508df">

### Different discrete bar charts

<img width="774" alt="Screenshot 2024-08-28 at 07 18 48" src="https://github.com/user-attachments/assets/12547a6a-0635-43a1-ba15-8e049b86a3a2">
<img width="774" alt="Screenshot 2024-08-28 at 07 18 51" src="https://github.com/user-attachments/assets/27813a68-a41d-4ae9-97d7-de71fac89ffc">
<img width="774" alt="Screenshot 2024-08-28 at 07 18 59" src="https://github.com/user-attachments/assets/5c5ad4a7-93c2-4181-afa5-933de5b2ec78">
<img width="774" alt="Screenshot 2024-08-28 at 07 19 06" src="https://github.com/user-attachments/assets/06521e48-4428-474f-964f-7f93e476e59c">

</details>

2024-08-31 20:12 UTC, toni-sharpe commented
@danyx23 hello :-)

The new tag and system underneath (which addressed [my concern here](https://github.com/owid/owid-grapher/issues/3878)) is great, but I noitice this PR doesn't have it applied?

Perhaps it could auto-apply if the contribution is not part of some team, or, the contriubutor could have access to add it themselves?

@lucasrodes @sophiamersmann tagged as you raised the two issues I think I fixed with this PR

2024-09-02 11:18 UTC, sophiamersmann requested changes
Thank you for the fix! I think adding `nowrap` to the time notice cell should be all that is needed here.

> * changed `400px` to `80vw` which is more responsive anyway, but was also needed to catch longer rows with dates

Can you change this back to 400px? Using a fixed width makes more sense here.

> * `white-space: nowrap` kept the date from breaking line

This works well!

> * combining the swatch colour with name avoided the problem with `<table />` guessing at widths which made a huge gap between swatch and name

I'm not sure what you mean, but the changes mess with the layout of the "Total" row. Can you please revert?

2024-09-02 17:47 UTC, toni-sharpe commented
@sophiamersmann - hello, hope you're well,

re: "combining the swatch colour  .... huge gap between swatch and name" - this was occuring in cases where 80vw made the table much wider, below is an example:

<img width="400" alt="Screenshot 2024-09-02 at 19 43 37" src="https://github.com/user-attachments/assets/4d982b56-6f3b-44ed-9a0a-fd8da2845bdc">

But fixing it to `400px` again stops this issue.

As you observe, the `nowrap` alone _seems_ to get everything in both issues, so I've pushed up reverts for the two commits.

2024-09-03 06:58 UTC, sophiamersmann commented
I can see that you reverted the commits, but somehow, the changes still show up in the diff. Once that's sorted, I'm happy to merge.

---

This is how the formatting of the total row changed:

| What it should be  | What it looked like  |
| ------- | ------ |
| <img width="1078" alt="Screenshot 2024-09-02 at 12 52 34" src="https://github.com/user-attachments/assets/dc4f7a84-37d2-4c5a-8a9b-540e4fe89153">  | <img width="1078" alt="Screenshot 2024-09-02 at 12 52 27" src="https://github.com/user-attachments/assets/c235a555-5d4e-4143-ac03-59ee018c7c45"> |

2024-09-03 11:44 UTC, toni-sharpe commented
@sophiamersmann not sure I'm even seeing that row:

But I can see that `git revert` hasn't undone the commits as I expected, the code itself hasn't changed. 

I'll get this sorted later today (have to go out) but well beyond business hours.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/4f76948c-13be-4fd0-aa9d-4a4040aca4cb">

2024-09-03 18:15 UTC, toni-sharpe commented
@sophiamersmann this should now be done (though I have not tested in your issue's context)

You now have one **commit that applies nowrap** to fix dates.

With your issue I assume it was just the date wrapping? Without testing, it should now have a flat date and wrapped text in the box. My `80vw` decision will have been for the text too. This is out of scope unless the text also is to be fixed.

2024-09-05 13:26 UTC, sophiamersmann approved these changes
Thank you!

2024-09-05 13:27 UTC, merged