🎉 automatic breadcrumbs from the tag graph
owid/owid-grapher pull request #4343
Opened 2024-12-19 23:57 UTC by ikesau

2024-12-23 13:47 UTC, danyx23 commented
Nice work! A few notes from playing with it: I think it would be great if there were an easier way in the admin to understand if breadcrumbs were set automatically or manually. 

The final leaf node not being shown is understandable but quite an inconsistency. It might work well to use the slug, split by dash and sentence cased? E.g. "us-airline-travel" -> "Us airline travel". This will clearly sometimes not be perfect but this is what manual overrides are for. What do you think?

My hunch is also that we should advertise this staging server quite prominently after the christmas break - I'm pretty sure that Joe, Ed and maybe Max will want to look at quite a few examples to get a feeling for the logic. I think it works very well (e.g. the tie breaking etc) but I anticipate some discussion there.

2024-12-23 14:09 UTC, danyx23 reviewed
The types in getParentTagArraysByChildName should be a bit more explicit IMHO, otherwise this looks good! 

As I wrote above, I think the semantics of this PR will warrant a bit of scrutiy and discussion and this might mean a few more code changes - if so, ping me again quickly before this gets merged.

2024-12-23 14:09 UTC, danyx23 commented on adminSiteServer/app.test.tsx
> +describe.only("OwidAdminApp: tag graph", () => {
Really nice tests!

2025-01-09 23:16 UTC, ikesau commented
Hey @danyx23 🙂 

Updates:
- Renames the `posts_gdocs` `breadcrumbs` column to `manualBreadcrumbs` to disambiguate it from automatic breadcrumbs throughout the codebase
  - Fixes various overlooked admin preview bugs that were due to these getting mixed up
- Adds a migration to delete the ~30 manually set breadcrumbs for non-SDG articles to ensure "no last node" consistency for all non-SDG breadcrumbs ([Marwa's okay with this](https://owid.slack.com/archives/C03SK89695E/p1736286406486459))
- Updates CSS
- Improves admin UI to make it clearer where breadcrumbs are coming from


https://github.com/user-attachments/assets/65ea387a-714d-4152-b902-a09db5ead573

2025-01-14 11:28 UTC, danyx23 commented
The automatic breadcrumbs work fine AFAICS but the manual ones have two weirdnesses about them:
- When you edit them, you don't immediately see any changes. At least when clicking on "done" I would like the preview to be refreshed. I also don't understand why we have both "done" and "save draft" at this point. I think we should fold the behaviour of "save draft" into the "done" button. Happy to chat about the details of this.
- The other one is that it seems impossible to recreate the behaviour of the current automatic breadcrumbs with manual breadcrumbs. I can leave the last field empty but it still renders a ">" to an empty string in the breadcrumbs in that case. I'd also like to have better instructions for how to fill this in when the manual breadcrumbs is active (something like "Keep the last item empty unless you are editing an SDG page. See the writing guildelines for recommendations for how to pick topic parents")

Once these are tackled this is good to merge!

2025-01-14 11:28 UTC, danyx23 requested changes
The automatic breadcrumbs work fine AFAICS but the manual ones have two weirdnesses about them:

- When you edit them, you don't immediately see any changes. At least when clicking on "done" I would like the preview to be refreshed. I also don't understand why we have both "done" and "save draft" at this point. I think we should fold the behaviour of "save draft" into the "done" button. Happy to chat about the details of this.
- The other one is that it seems impossible to recreate the behaviour of the current automatic breadcrumbs with manual breadcrumbs. I can leave the last field empty but it still renders a ">" to an empty string in the breadcrumbs in that case. I'd also like to have better instructions for how to fill this in when the manual breadcrumbs is active (something like "Keep the last item empty unless you are editing an SDG page. See the writing guildelines for recommendations for how to pick topic parents")

Once these are tackled this is good to merge!

2025-01-16 14:28 UTC, merged